### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mbower** [Te-k/harpoon#98] opened 2018-09-11 13:32 UTC
OS: MacOS 10.13.6
python3 --version: Python 3.7.0

Im getting the following error after installing on MacOS and running "harpoon config":

```
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/harpoon/main.py", line 31, in main
    plugins = init_plugins()
  File "/usr/local/lib/python3.7/site-packages/harpoon/main.py", line 18, in init_plugins
    mod = __import__(plugin)
  File "/usr/local/lib/python3.7/site-packages/harpoon/commands/twitter.py", line 4, in <module>
    import tweepy
  File "/usr/local/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/usr/local/lib/python3.7/site-packages/tweepy/streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax
```

**Comment by Te-k** [comment] 2018-09-11 13:59
Nice that you are beta-testing python 3.7, the problem is that tweepy [doesn't support python 3.7](https://github.com/tweepy/tweepy/issues/1063). So I guess you will have to use python 3.5 or 3.6 (I have only tested in with 3.5)

**Comment by BORN2LOSE** [comment] 2018-10-15 10:38
@Te-k Python 3.7 was released on June 27, 2018.
Release Date: 2018-06-27
https://www.python.org/downloads/release/python-370/

**Comment by Harmon758** [comment] 2018-11-28 08:55
This should be resolved by the [3.7.0 release of Tweepy](https://github.com/tweepy/tweepy/releases/tag/3.7.0).

**Comment by Te-k** [comment] 2018-12-02 21:11
Thanks @Harmon758 for sharing that, it should indeed solve this issue. I will try to come up with a fix when I have time. Feel free to submit a PR anyone.

**Comment by Te-k** [comment] 2020-11-07 00:55
It should be solved with the last commit, feel free to reopen if you have this issue again

**Closed by Te-k** 2020-11-07 00:55 UTC
Labels: bug
