### ISSUE TITLE
harpoon config -u doesn't create required directory

### ISSUE THREAD

**Issue by deadbits** [Te-k/harpoon#54] opened 2018-02-27 16:29 UTC
After following the pip install, npm install directions, running `harpoon config -u` throws the following error since the directory `~/.config/harpoon` does not exist. This should ideally be created when running the config command so the downloaded files have somewhere to go - or check if it exists / prompt the user to create it for them

```
$ harpoon config -u
Updating all plugins data:
Updating plugin ip
Downloading MaxMind GeoIP Database
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.6/site-packages/harpoon/main.py", line 52, in main
    plugins[args.command].run(config, args, plugins)
  File "/usr/local/lib/python3.6/site-packages/harpoon/commands/config.py", line 66, in run
    plugins[p].update()
  File "/usr/local/lib/python3.6/site-packages/harpoon/commands/ip.py", line 85, in update
    with open(self.geocity, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/adam/.config/harpoon/GeoLite2-City.mmdb'
```

**Comment by Te-k** [comment] 2018-02-27 19:47
It was fixed by @Neo23x0 in the last pull request, the last version should work

**Comment by deadbits** [comment] 2018-02-27 19:56
Are you referring to this PR? https://github.com/Te-k/harpoon/pull/53
If so, I don't think it fixed the issue since I just downloaded and installed Harpoon a few hours ago and that PR was merged yesterday.  I think it looks like the PR covered the creation of the files but not the harpoon directory itself

**Comment by deadbits** [comment] 2018-02-27 19:58
I haven't looked at the code too closely yet tbh so I'm not 100% sure about my last comment but that seems to be the case since it was the directory not existing that was the problem. Later tonight I can look through the code and probably just put in a PR if this is whats going on

**Comment by Te-k** [comment] 2018-02-27 20:18
Ah the problem is likely that I do not check that `.config/harpoon` exist before creating the files. Can you try if `.config` and `.config/harpoon` exist on your system?
I have just fixed that, so if I am right it should be fixed

**Comment by deadbits** [comment] 2018-02-28 13:44
Yup that takes care of it in your latest commit and change to config.py with that os.makedirs if statement

The .config folder should exist on pretty much all OSX or Linux systems but it was just getting hung up on the harpoon sub directory.
Thanks for the quick response to this and of course for the sweet project! :)

**Comment by Te-k** [comment] 2018-02-28 16:26
Cool, so it's working now ?

**Comment by deadbits** [comment] 2018-02-28 16:31
Yup, all set we can close this down. I was going to in my last comment but didn't know if you wanted to change labels or anything before it was closed out, etc.

While we're chatting, are you open to PRs for some of the open issues you have for new API modules (ipinfo, etc?)

**Comment by Te-k** [comment] 2018-02-28 18:20
Yes, please feel free to submit PRs, there is definitely more dev than I will be able to do

**Closed by Te-k** 2018-02-28 18:20 UTC
Labels: bug, waiting for feedback
