### ISSUE TITLE
installation fails on fresh ubuntu install

### ISSUE THREAD

**Issue by grispan56** [Te-k/harpoon#93] opened 2018-08-28 19:43 UTC
the documentation should state that on linux (ubuntu/debian) its needed to install the dev toos which are not installed by default for the app to work.

apt-get install python3-dev

otherwise errors about missing files will appear during

**Comment by grispan56** [comment] 2018-08-30 21:01
tried on different installations, all failed the same error of telegram ?

`root@cf24dce1404f:~/harpoon# harpoon config    
Traceback (most recent call last):
  File "/usr/local/bin/harpoon", line 11, in <module>
    load_entry_point('harpoon==0.1.1', 'console_scripts', 'harpoon')()
  File "/usr/local/lib/python3.6/dist-packages/harpoon/main.py", line 31, in main
    plugins = init_plugins()
  File "/usr/local/lib/python3.6/dist-packages/harpoon/main.py", line 18, in init_plugins
    mod = __import__(plugin)
  File "/usr/local/lib/python3.6/dist-packages/harpoon/commands/telegram.py", line 12, in <module>
    from telethon.errors.rpc_error_list import ChatAdminRequiredError
ModuleNotFoundError: No module named 'telethon.errors.rpc_error_list'
`

**Comment by Te-k** [comment] 2018-08-31 10:45
Hi,
Thanks, I just updated the install instructions to add `python3-dev` install.

The last issue is related to #87, can you do `pip uninstall Telethon` and then `pip install Telethon==0.18.3` (harpoon only works with the version 0.18.3 of Telethon, I just updated the requirements)

**Comment by Te-k** [comment] 2019-01-31 22:42
It should be solved now, I am closing the issue, feel free to reopen it if the problem is still there

**Closed by Te-k** 2019-01-31 22:42 UTC
Labels: bug, waiting for feedback
